version: 2.1
orbs:
  php: circleci/php@1
jobs:
  test-php:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - php/install-packages
      - run:
          name: "Install Composer"
          command: "curl -sS https://getcomposer.org/installer | php ----install-dir=/usr/local/bin -filename=composer"
      - run:
          name: "Setup env"
          command: "cp .env.example .env"
      - run:
          name: "Install Dependencies"
          command: "composer install --ignore-platform-req=ext-pcntl"
      - run:
        name: "Run Tests"
        command: "php artisan test"
